FROM golang:1.22-alpine
WORKDIR /app

RUN apk add --no-cache gcc musl-dev git

# Install air for hot reloading
RUN go install github.com/air-verse/air@latest

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
