FROM golang:1.26.8-alpine3.23
WORKDIR /app

RUN apk add --no-cache gcc musl-dev git

# Install air for hot reloading
RUN go install github.com/air-verse/air@v1.62.0

EXPOSE 3000

CMD ["air", "-c", ".air.toml"]
