package main

import (
	"bufio"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/url"
	"os"
	"path/filepath"
	"strings"
)

const (
	defaultPort             = "3000"
	defaultDatabasePath     = "/data/chromatic.db"
	defaultUploadPath       = "/data/files"
	defaultLogoPath         = "/data/logos"
	defaultOBSReconnect     = "5m"
	defaultClientPing       = "60s"
	defaultPublicURLProd    = "https://stream.yourdomain.com"
	defaultPublicURLDev     = "http://localhost:3000"
	defaultTurnRealmProd    = "stream.yourdomain.com"
	defaultTurnRealmDev     = "localhost"
	defaultEnvRelativePath  = "deployments/.env"
	defaultAllowedOrigins   = "https://stream.yourdomain.com"
	defaultExternalTurnURL  = ""
	defaultExternalTurnUser = ""
	defaultExternalTurnPass = ""
)

func runSetup() int {
	reader := bufio.NewReader(os.Stdin)

	fmt.Println("Chromatic setup wizard")
	fmt.Println("This will create a .env file for Docker or local deployment.")
	fmt.Println("")

	envPath := defaultEnvRelativePath
	if !promptYesNo(reader, "Write config to deployments/.env", true) {
		envPath = prompt(reader, "Enter .env path", envPath)
	}
	envPath = strings.TrimSpace(envPath)
	if envPath == "" {
		fmt.Println("No path provided. Aborting.")
		return 1
	}

	if _, err := os.Stat(envPath); err == nil {
		if !promptYesNo(reader, "File exists. Overwrite", false) {
			fmt.Println("Setup cancelled.")
			return 1
		}
	}

	productionMode := promptYesNo(reader, "Production mode", true)

	publicURLDefault := defaultPublicURLProd
	if !productionMode {
		publicURLDefault = defaultPublicURLDev
	}
	publicURL := requireValue(reader, "PUBLIC_URL", publicURLDefault)

	turnRealmDefault := defaultTurnRealmProd
	if !productionMode {
		turnRealmDefault = defaultTurnRealmDev
	}
	if host := hostFromURL(publicURL); host != "" {
		turnRealmDefault = host
	}
	turnRealm := requireValue(reader, "TURN_REALM", turnRealmDefault)

	adminToken := promptSecret(reader, "ADMIN_TOKEN", true)
	turnSecret := promptSecret(reader, "TURN_SECRET", true)

	allowedOrigins := ""
	if productionMode {
		defaultOrigins := defaultAllowedOrigins
		if publicURL != "" {
			defaultOrigins = publicURL
		}
		allowedOrigins = requireValue(reader, "ALLOWED_ORIGINS (comma-separated)", defaultOrigins)
	}

	trustedProxies := prompt(reader, "TRUSTED_PROXIES (optional)", "")
	publicIP := prompt(reader, "PUBLIC_IP (optional, recommended for TURN)", "")

	externalTurnURL := defaultExternalTurnURL
	externalTurnUser := defaultExternalTurnUser
	externalTurnPass := defaultExternalTurnPass
	if promptYesNo(reader, "Configure external TURN provider", false) {
		externalTurnURL = requireValue(reader, "TURN_EXTERNAL_URL", "")
		externalTurnUser = requireValue(reader, "TURN_EXTERNAL_USER", "")
		externalTurnPass = requireValue(reader, "TURN_EXTERNAL_PASS", "")
	}

	content := buildEnvFile(envFileParams{
		adminToken:          adminToken,
		publicURL:           publicURL,
		turnSecret:          turnSecret,
		turnRealm:           turnRealm,
		productionMode:      productionMode,
		allowedOrigins:      allowedOrigins,
		trustedProxies:      trustedProxies,
		databasePath:        defaultDatabasePath,
		uploadPath:          defaultUploadPath,
		logoPath:            defaultLogoPath,
		port:                defaultPort,
		publicIP:            publicIP,
		turnExternalURL:     externalTurnURL,
		turnExternalUser:    externalTurnUser,
		turnExternalPass:    externalTurnPass,
		obsReconnectTimeout: defaultOBSReconnect,
		clientPingInterval:  defaultClientPing,
	})

	if err := os.MkdirAll(filepath.Dir(envPath), 0755); err != nil {
		fmt.Printf("Failed to create directory: %v\n", err)
		return 1
	}

	if err := os.WriteFile(envPath, []byte(content), 0600); err != nil {
		fmt.Printf("Failed to write %s: %v\n", envPath, err)
		return 1
	}

	fmt.Println("")
	fmt.Printf("Wrote %s\n", envPath)
	fmt.Println("Restart Chromatic after applying the new environment.")
	return 0
}

type envFileParams struct {
	adminToken          string
	publicURL           string
	turnSecret          string
	turnRealm           string
	productionMode      bool
	allowedOrigins      string
	trustedProxies      string
	databasePath        string
	uploadPath          string
	logoPath            string
	port                string
	publicIP            string
	turnExternalURL     string
	turnExternalUser    string
	turnExternalPass    string
	obsReconnectTimeout string
	clientPingInterval  string
}

func buildEnvFile(p envFileParams) string {
	var b strings.Builder
	writeLine := func(line string) {
		b.WriteString(line)
		b.WriteString("\n")
	}

	writeLine("# Chromatic Environment Configuration")
	writeLine("# Generated by `chromatic setup`")
	writeLine("")
	writeLine("# =============================================================================")
	writeLine("# REQUIRED SETTINGS")
	writeLine("# =============================================================================")
	writeLine(fmt.Sprintf("ADMIN_TOKEN=%s", p.adminToken))
	writeLine(fmt.Sprintf("PUBLIC_URL=%s", p.publicURL))
	writeLine(fmt.Sprintf("TURN_SECRET=%s", p.turnSecret))
	writeLine(fmt.Sprintf("TURN_REALM=%s", p.turnRealm))
	writeLine("")
	writeLine("# =============================================================================")
	writeLine("# PRODUCTION SETTINGS")
	writeLine("# =============================================================================")
	writeLine(fmt.Sprintf("PRODUCTION_MODE=%t", p.productionMode))
	if p.allowedOrigins != "" {
		writeLine(fmt.Sprintf("ALLOWED_ORIGINS=%s", p.allowedOrigins))
	} else {
		writeLine("ALLOWED_ORIGINS=")
	}
	writeLine(fmt.Sprintf("TRUSTED_PROXIES=%s", p.trustedProxies))
	writeLine("")
	writeLine("# =============================================================================")
	writeLine("# STORAGE PATHS (Docker volume mounts)")
	writeLine("# =============================================================================")
	writeLine(fmt.Sprintf("DATABASE_PATH=%s", p.databasePath))
	writeLine(fmt.Sprintf("UPLOAD_PATH=%s", p.uploadPath))
	writeLine(fmt.Sprintf("LOGO_PATH=%s", p.logoPath))
	writeLine("")
	writeLine("# =============================================================================")
	writeLine("# SERVER SETTINGS")
	writeLine("# =============================================================================")
	writeLine(fmt.Sprintf("PORT=%s", p.port))
	writeLine(fmt.Sprintf("PUBLIC_IP=%s", p.publicIP))
	writeLine("")
	writeLine("# =============================================================================")
	writeLine("# EXTERNAL TURN SERVER (Optional)")
	writeLine("# =============================================================================")
	writeLine(fmt.Sprintf("TURN_EXTERNAL_URL=%s", p.turnExternalURL))
	writeLine(fmt.Sprintf("TURN_EXTERNAL_USER=%s", p.turnExternalUser))
	writeLine(fmt.Sprintf("TURN_EXTERNAL_PASS=%s", p.turnExternalPass))
	writeLine("")
	writeLine("# =============================================================================")
	writeLine("# TIMEOUTS")
	writeLine("# =============================================================================")
	writeLine(fmt.Sprintf("OBS_RECONNECT_TIMEOUT=%s", p.obsReconnectTimeout))
	writeLine(fmt.Sprintf("CLIENT_PING_INTERVAL=%s", p.clientPingInterval))
	return b.String()
}

func prompt(reader *bufio.Reader, label, defaultValue string) string {
	if defaultValue != "" {
		fmt.Printf("%s [%s]: ", label, defaultValue)
	} else {
		fmt.Printf("%s: ", label)
	}
	text, _ := reader.ReadString('\n')
	text = strings.TrimSpace(text)
	if text == "" {
		return defaultValue
	}
	return text
}

func requireValue(reader *bufio.Reader, label, defaultValue string) string {
	for {
		value := prompt(reader, label, defaultValue)
		if strings.TrimSpace(value) != "" {
			return value
		}
		fmt.Println("Value is required.")
	}
}

func promptYesNo(reader *bufio.Reader, label string, defaultYes bool) bool {
	suffix := "y/N"
	if defaultYes {
		suffix = "Y/n"
	}
	for {
		fmt.Printf("%s (%s): ", label, suffix)
		text, _ := reader.ReadString('\n')
		text = strings.TrimSpace(strings.ToLower(text))
		if text == "" {
			return defaultYes
		}
		if text == "y" || text == "yes" {
			return true
		}
		if text == "n" || text == "no" {
			return false
		}
		fmt.Println("Please enter y or n.")
	}
}

func promptSecret(reader *bufio.Reader, label string, allowGenerate bool) string {
	if allowGenerate && promptYesNo(reader, fmt.Sprintf("Generate %s", label), true) {
		token, err := generateHex(32)
		if err != nil {
			fmt.Printf("Failed to generate %s: %v\n", label, err)
		} else {
			return token
		}
	}
	return requireValue(reader, label, "")
}

func generateHex(bytesCount int) (string, error) {
	b := make([]byte, bytesCount)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

func hostFromURL(raw string) string {
	candidate := strings.TrimSpace(raw)
	if candidate == "" {
		return ""
	}
	if !strings.Contains(candidate, "://") {
		candidate = "https://" + candidate
	}
	parsed, err := url.Parse(candidate)
	if err != nil {
		return ""
	}
	return parsed.Hostname()
}
